#!/bin/bash

if [ $# -ne 3 ]
then
    echo "Usage: $0 <network address> <subnet mask> <parallelism>"
    exit 1
fi

network=$1
subnet_mask=$2
parallelism=$3

IFS=. read -r a b c d <<< "$network"
IFS=. read -r m1 m2 m3 m4 <<< "$subnet_mask"

# Compute network address and broadcast address
network_addr="$((a & m1)).$((b & m2)).$((c & m3)).$((d & m4))"
broadcast_addr="$(((a & m1) | (255 - m1))).$(((b & m2) | (255 - m2))).$(((c & m3) | (255 - m3))).$(((d & m4) | (255 - m4)))"

# Generate list of IP addresses to ping
ip_list=""
for ((i=$(($d & $m4)); i<$(($d | (255 - $m4) + 1)); i++))
do
    ip="$((a & m1)).$((b & m2)).$((c & m3)).$i"
    ip_list="$ip_list $ip"
done

# Ping all IP addresses in parallel linux version
# echo "$ip_list" | tr ' ' '\n' | parallel -j$parallelism --timeout 1 "ping -c1 {} >/dev/null && echo {} is up || echo {} is down"
# Ping all IP addresses in parallel mac os version
echo "$ip_list" | tr ' ' '\n' | parallel -j$parallelism --timeout 1 "ping -t1 {} >/dev/null && echo {} is up || echo {} is down"
