#!/bin/bash

for i in {1..254}
do
    ip="192.168.1.$i"
    # ping -c 1 $ip > /dev/null linux version
    ping -t 1 $ip > /dev/null
    if [ $? -eq 0 ]
    then
        echo "$ip is up"
    else
        echo "$ip is down"
    fi
done
